aws-api:
  region: "US_EAST_1"
  default-voice: "Brian"
  default-effects:
    type: prosody
    volume: medium
    pitch: default
    rate: medium
  voice-prefixes:
    Sal: Salli
    Kim: Kimberly
    Bri: Brian
twitch-api:
  enable: false
  messages:
    send: false
    clean-markdown: true
  channel: ""
  username: ""
  chat:
    default:
      format: "%user% ➜ %message%"
      weight: 0
      permission: EVERYONE
    mod:
      format: "<br-green>⚔ %user%</color> ➜ %message%"
      weight: 10
      permission: MODERATOR
speech-effect-markdown:
  "**":
    type: prosody
    volume: x-loud
    pitch: low
    rate: slow
  "~~":
    type: amazon:effect
    name: whispered
  "__":
    type: emphasis
    level: strong
  "*":
    type: prosody
    volume: x-loud
    rate: x-fast
    pitch: x-high
  "||":
    type: say-as
    interpret-as: expletive
text-replacements:
    "<3": "heart emoji"
internal-settings:
  server-port: 3000
  twitch-auth-port: 8080
